{"name": "test_case6", "status": "failed", "statusDetails": {"message": "AssertionError: assert 5 == 7\n +  where 7 = add(4, 3)", "trace": "def test_case6():\n>       assert 5 == add(4, 3)\nE       assert 5 == 7\nE        +  where 7 = add(4, 3)\n\ntest_use_allure.py:33: AssertionError"}, "start": 1690273914512, "stop": 1690273914513, "uuid": "7aceebb4-b1b6-48f2-9674-a0d16ea6184f", "historyId": "02e8ac7a2a886562c30248a390c4cb65", "testCaseId": "6b851befa184d5b9e1fdadbc532eba51", "fullName": "test_use_allure#test_case6", "labels": [{"name": "suite", "value": "test_use_allure"}, {"name": "host", "value": "DESKTOP-BVMI6KU"}, {"name": "thread", "value": "11496-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_use_allure"}]}